name: Java CI

on: [ push ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '21' ]
    name: Java ${{ matrix.java }} Zulu build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn  -DskipTests clean package
    